apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp-image
        image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: aspnetapp
spec:
    selector:
        app: aspnetapp
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
    type: LoadBalancer